version: '3.8'

services:
  # Main application container with frontend and backend
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - PYTHONPATH=/app/backend
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - qdrant
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:v1.7.4
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334

volumes:
  qdrant_data:

networks:
  default:
    driver: bridge